[dataset]
    path = "/data/tuxai/dataset"

[diskcache]
    path = "/data/tuxai/cache"
    size_limit = 20e9

[kernel]
    # for url template, check https://www.kernel.org/ tarball links (may be modified)
    # tar_url = "https://git.kernel.org/torvalds/t/linux-$major.$minor.tar.gz"
    tar_url = "https://cdn.kernel.org/pub/linux/kernel/v$major.x/linux-$major.$minor.tar.gz"
    path = "/data/tuxai/kernel"
    kconfig_arch_whitelist = ["x86"]  # when /arch/ in path
    kconfig_blacklist = ["kconfig-language"]

[dataframe]
    targets = [
        "vmlinux",
        "GZIP-bzImage", 
        "GZIP-vmlinux", 
        "GZIP", 
        "BZIP2-bzImage", 
        "BZIP2-vmlinux", 
        "BZIP2", 
        "LZMA-bzImage", 
        "LZMA-vmlinux", 
        "LZMA", 
        "XZ-bzImage", 
        "XZ-vmlinux", 
        "XZ", 
        "LZO-bzImage", 
        "LZO-vmlinux", 
        "LZO", 
        "LZ4-bzImage", 
        "LZ4-vmlinux", 
        "LZ4"
    ]

    extras = ["cid", "active_options"]

[report]
    versions = [413, 415, 420, 500, 504, 507, 508]
    # xgboost_targets = ["vmlinux", "GZIP-vmlinux", "BZIP2-vmlinux", "LZMA-vmlinux", "XZ-vmlinux", "LZO-vmlinux", "LZ4-vmlinux"]
    all_targets = ["vmlinux", "GZIP", "BZIP2", "LZMA", "XZ", "LZO", "LZ4"]
    targets = ["vmlinux", "XZ-vmlinux"]  # light list, since compressed targets are correlated
    unique_compressed_target = "XZ-vmlinux"

    # targets = ["vmlinux", "XZ"]
    # feature_limit = -1  # no limit
    # top_feature_count = 50
    yes_no_ratio_threshold = 0.1   



[log]
    path = "/data/tuxai/logs/log.txt"
    terminal_level = "info"
    #terminal_level = "debug"
    file_level = "debug"
    file_size = 10000000
    file_count = 3

